version: '2'
services:
    account-app:
        image: account
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
